# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#inputs
# https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runs-for-composite-run-steps-actions

name: "PHPUnit Test segmentation"

description: "Returns a JSON string of PHPUnit test segments that can be used as a matrix for GithubActions."

inputs:
  phpunit-path:
    description: "Path to phpunit"
    required: false
    default: "vendor/bin/phpunit"
  strategy:
    description: "Segmentation strategy, e.g. 'groups' or 'testsuites'"
    required: true

outputs:
  segments-json:
    description: "JSON string of segments"
    value: ${{ steps.determine-segments.outputs.json }}

runs:
  using: "composite"

  steps:
    - name: "Determine segments"
      id: determine-segments
      env:
        PHPUNIT_PATH: "${{ inputs.phpunit-path }}"
        SEGMENTATION_STRATEGY: "${{ inputs.strategy }}"
      run: echo "json=$(php ${{github.action_path}}/phpunit-segment.php)" >> $GITHUB_OUTPUT
      shell: bash